#!/bin/sh

##########################################
# Set environment variables
##########################################

# e.g. SBBINDIR=/opt/sb/egibson/linux or /windows or /unix
# SBBINDIR must contain /SB and /.FSLSB and /.HFB
if [ ${SBBINDIR}x = "x" ]; then echo "Error:  SBBINDIR enviornment variable is not set"; exit; fi

##########################################
# Define functions
##########################################

usage(){
  cmdname=`basename ${0}`
  echo "Usage:"
  echo "  ${cmdname} -t1 <ACPC_T1> -mat <ACPCtoT1.air>" 
  echo "               -grid <grid.txt> -out <cf> -cing <cingulate>"
  echo ""
  echo " -mat:  (ACPC-to-T1 rotation matrix, required)"
  echo " -grid: (lobmask grid text file, required)"
  echo " -out:  (output prefix, required)"
  echo " -cing: (cingulate mask image, optional)"
  echo " -lob:  (ACPC lobmask image, required)"
  echo " -t1acq:(T1 acquisition image, not usually required)"
  echo ""
  echo "Purpose:"
  echo " -parcellate the cholinergic fibers into 2 regions"
  echo ""
  echo "Notes"
  echo " -the cingulate mask is optional, but if omitted, only a partial segmentation"
  echo "  of the cholinergic fibers will be performed (i.e. the cingulate mask is"
  echo "  necessary to segment the superior cholinergic fibers)"
  echo ""
  exit
}

parse_arguments(){
  while [ ${#} -gt 0 ]
  do
    case ${1} in
    -out)
      shift; out=`echo ${1} | sed "s/\.img$//" | sed "s/\.hdr$//" | sed "s/\.$//"`; shift;;
    -lob)
      shift; lob=`echo ${1} | sed "s/\.img$//" | sed "s/\.hdr$//" | sed "s/\.$//"`; shift;;
    -cing)
      shift; cing=`echo ${1} | sed "s/\.img$//" | sed "s/\.hdr$//" | sed "s/\.$//"`; shift;;
     -mat)
      shift; mat=`echo ${1}`; shift;;
     -grid)
      shift; grid=`echo ${1}`; shift;;
    -help)
      usage;;
    *)
      echo "Error: unknown option ${1}"; exit;;
    esac
  done
}

check_analyze(){
  if [ ! -f ${1}.img ]; then echo "Error:  ${1}.img not found"; exit; fi
  if [ ! -f ${1}.hdr ]; then echo "Error:  ${1}.hdr not found"; exit; fi
  if [ ${2}x != "x" ];  then echo "Error: Multiple files detected: ${*}"; exit; fi
}

check_file(){
  if [ ${1}x = "x" ]; then echo "Error: file not found"; exit; fi
  if [ ! -f ${1} ];   then echo "Error: ${1} not found"; exit; fi
  if [ ${2}x != "x" ]; then echo "Error: multiple files detected: ${*}"; exit; fi
}

##########################################
# Verify Input
##########################################
if [ ${#} -lt 5 ]; then usage; fi

parse_arguments ${*}

if [ ${out}x = "x" ];   then echo "Error:  Must supply -out option"; exit; fi;
if [ ${mat}x = "x" ];  then echo "Error:  Must supply -mat option"; exit; fi;
if [ ${grid}x = "x" ];  then echo "Error: Must supply -grid option"; exit; fi;
if [ ${lob}x = "x" ]; then echo "Error: Must supply -lob option"; exit; fi
if [ ${t1acq}x = "x" ]; then t1acq=`ls *T1acq_lobmask_filled.img | sed "s/\.img//" 2>/dev/null`; fi
if [ ${t1acq}x = "x" ]; then echo "Error: could not guess T1 acquisition image, use -t1acq option"; exit; fi
if [ ${cing}x = "x" ]; then rough_estimate="true"; fi;

check_analyze ${lob}; check_file ${mat}; check_file ${grid}; check_analyze ${t1acq}
if [ ${cing}x != "x" ]; then check_analyze ${cing}; fi;

##########################################
# Start processing
##########################################

${SBBINDIR}/SB/bin/getBGT ${lob} temp_basal_ganglia_mask

if [ ${rough_estimate}x = "x" ]; then

  echo "Creating cholinergic fibers mask with cingulate mask"

  ${SBBINDIR}/SB/bin/lobmaskCF temp_basal_ganglia_mask ${cing} ${out}_acpc -g ${grid}

  ${SBBINDIR}/SB/bin/areslice ${out}_acpc.img ${t1acq}.img ${mat} ${out}.img -nn
  
else

  echo "Creating cholinergic fibers mask without cingulate mask"
  echo "For better regional parcellation, run again using cingulate mask"
  
  ${SBBINDIR}/SB/bin/lobmaskCF2 temp_basal_ganglia_mask ${out}_acpc -g ${grid}

  ${SBBINDIR}/SB/bin/areslice ${out}_acpc.img ${t1acq}.img ${mat} ${out}.img -nn

  
fi

rm temp_basal_ganglia_mask.*