#!/bin/sh



# Check for SBBINDIR environment variable
if [ ${SBBINDIR}x = "x" ]
then
  echo "Error:  SBBINDIR enviornment variable is not set"
  exit
fi

# Configure FSL 
FSLDIR=${SBBINDIR}/.FSLSB
export FSLDIR
FSLOUTPUTTYPE=ANALYZE
export FSLOUTPUTTYPE
FSLBINDIR=${FSLDIR}/bin




# Get options for fast command, if given
opts=""
for arg in ${*}
do
  opts="${opts} ${arg}"
done


#***********************************************************************************#
#***********************************************************************************#

# Run avwmaths_16SI 

${FSLBINDIR}/avwmaths_16SI ${opts} 


