#Compile with gcc-2.95

#CXX=/home116/egibson/openSuSE9.0/gcc-2.95.2.1-bin/bin/g++
CXXFLAGS=-O2 

all: lobmask_istl

lobmask_istl:
	$(CXX) lobmask_istl.cpp $(CXXFLAGS) -o $@

clean:
	rm -rf lobmask_istl

